name: Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-docker-image:
    name: Build image and push to container registry

    strategy:
      matrix:
        include:
          - arch: amd64
            mode: build-and-test
          - arch: arm64
            variant: v8
            mode: build-only

    runs-on: ubuntu-latest

    env:
      PLATFORM: linux/${{ matrix.arch }}${{ (matrix.variant != '' && format('/{0}', matrix.variant)) || '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to container registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name}}
            ghcr.io/${{ github.repository }}:latest
